[package]
name = "itsboard-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
panic-halt = "0.2.0"

[dependencies.stm32f4]
version = "0.14.0"
features = ["stm32f429"]

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
