[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3.1"
libm = "0.2.15"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["image", "unsafe_textures"]
